### ISSUE TITLE
貌似失效了？

### ISSUE THREAD

**Issue by walkxspace** [WingLim/ddns-telegram-bot#3]
最开始 DDNS-GO 添加上本项目链接的一段时间内机器人的功能正常，但是貌似到现在至少有 1 周多连不上了，给机器人发送指令无响应，Webhook 地址也没有反映了。😅

**Comment by WingLim** [comment]
代码一直在重设 `webhook` 地址，导致消息发不到 Telegram Bot，现在已经修复了。
