### ISSUE TITLE
国内貌似屏蔽了项目TG机器人的服务器？

### ISSUE THREAD

**Issue by fejich** [WingLim/ddns-telegram-bot#4]
宽带运营商 广东电信

```
2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
```

TG上最后收到的消息是 2022年8月25 号。。。

---

在 US 的 VPS 上测试，能正常收到消息

**Comment by wukitest** [comment]
> 宽带运营商 广东电信
> 
> ```
> 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> ```
> 
> TG上最后收到的消息是 2022年8月25 号。。。
> 
> 在 US 的 VPS 上测试，能正常收到消息

国内墙了vercel.app这一域名

**Comment by wukibaka** [comment]
> 宽带运营商 广东电信
> 
> ```
> 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> ```
> 
> TG上最后收到的消息是 2022年8月25 号。。。
> 
> ---
> 
> 在 US 的 VPS 上测试，能正常收到消息

国内屏蔽了vercel.app这一域名

**Comment by wukibaka** [comment]
希望作者能教教怎么用vercel自己搭

**Comment by wukibaka** [comment]
> 宽带运营商 广东电信
> 
> ```
> 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> ```
> 
> TG上最后收到的消息是 2022年8月25 号。。。
> 
> ---
> 
> 在 US 的 VPS 上测试，能正常收到消息

自己研究了一下 搭了个bot 我这儿正常了 你试试吧
https://t.me/DDNS_Telegram_Bot

**Comment by shaojs321** [comment]
> > 宽带运营商 广东电信
> > ```
> > 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > TG上最后收到的消息是 2022年8月25 号。。。
> > 
> > 在 US 的 VPS 上测试，能正常收到消息
> 
> 自己研究了一下 搭了个bot 我这儿正常了 你试试吧 https://t.me/DDNS_Telegram_Bot

这个怎么自己部署啊，部署到vps或者vercel有文档吗

**Comment by wukibaka** [comment]
> > > 宽带运营商 广东电信
> > > ```
> > > 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > TG上最后收到的消息是 2022年8月25 号。。。
> > > 
> > > 在 US 的 VPS 上测试，能正常收到消息
> > 
> > 自己研究了一下 搭了个bot 我这儿正常了 你试试吧 https://t.me/DDNS_Telegram_Bot
> 
> 这个怎么自己部署啊，部署到vps或者vercel有文档吗

我有空写个教程吧

**Comment by shaojs321** [comment]
> > > > 宽带运营商 广东电信
> > > > ```
> > > > 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > TG上最后收到的消息是 2022年8月25 号。。。
> > > > 在 US 的 VPS 上测试，能正常收到消息
> > > 
> > > 
> > > 自己研究了一下 搭了个bot 我这儿正常了 你试试吧 https://t.me/DDNS_Telegram_Bot
> > 
> > 
> > 这个怎么自己部署啊，部署到vps或者vercel有文档吗
> 
> 我有空写个教程吧

> > > > 宽带运营商 广东电信
> > > > ```
> > > > 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > TG上最后收到的消息是 2022年8月25 号。。。
> > > > 在 US 的 VPS 上测试，能正常收到消息
> > > 
> > > 
> > > 自己研究了一下 搭了个bot 我这儿正常了 你试试吧 https://t.me/DDNS_Telegram_Bot
> > 
> > 
> > 这个怎么自己部署啊，部署到vps或者vercel有文档吗
> 
> 我有空写个教程吧

感谢大佬

**Comment by xuelang113** [comment]
大佬，出个搭建教程，等着呢

**Comment by xuelang113** [comment]
2022/12/19 15:41:18 请求接口 https://ddns.wuki.moe/api/hook/702539297 失败! 返回内容: A server error has occurred FUNCTION_INVOCATION_FAILED ,返回状态码: 500
2022/12/19 15:41:18 Webhook调用失败，Err：请求接口 https://ddns.wuki.moe/api/hook/702539297 失败! 返回内容: A server error has occurred FUNCTION_INVOCATION_FAILED ,返回状态码: 500
2022/12/19 15:41:37 连接失败! [点击查看接口能否返回IPv6地址](https://myip6.ipip.net/), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)

**Comment by wukibaka** [comment]
> 2022/12/19 15:41:18 请求接口 https://ddns.wuki.moe/api/hook/702539297 失败! 返回内容: A server error has occurred FUNCTION_INVOCATION_FAILED ,返回状态码: 500
> 2022/12/19 15:41:18 Webhook调用失败，Err：请求接口 https://ddns.wuki.moe/api/hook/702539297 失败! 返回内容: A server error has occurred FUNCTION_INVOCATION_FAILED ,返回状态码: 500
> 2022/12/19 15:41:37 连接失败! [点击查看接口能否返回IPv6地址](https://myip6.ipip.net/), 参考说明:[点击访问](https://github.com/jeessy2/ddns-go#%E4%BD%BF%E7%94%A8ipv6)

![Screenshot_20221220_075952.jpg](https://user-images.githubusercontent.com/51240031/208550971-a8a81ea8-2c26-4f5c-9893-2e65e8ea6bc0.jpg)
![Screenshot_20221220_075830.jpg](https://user-images.githubusercontent.com/51240031/208550862-16376aa5-565e-40b5-9fb3-4d07a8a2e845.jpg)
我这儿调用成功

**Comment by wukibaka** [comment]
> > > 宽带运营商 广东电信
> > > ```
> > > 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > TG上最后收到的消息是 2022年8月25 号。。。
> > > 
> > > 在 US 的 VPS 上测试，能正常收到消息
> > 
> > 自己研究了一下 搭了个bot 我这儿正常了 你试试吧 https://t.me/DDNS_Telegram_Bot
> 
> 这个怎么自己部署啊，部署到vps或者vercel有文档吗

教程写好了
https://github.com/wukibaka/ddns-telegram-bot/wiki/DDNS-TELEGRAM-BOT搭建教程
~~vercel更新导致用原教程部署的bot无法使用（已经部署好了的没影响）
可以先用我的bot
https://t.me/DDNS_Telegram_Bot
原教程已删除 等我有空了去更新下教程~~
教程已更新

**Comment by fejich** [comment]
> > > > 宽带运营商 广东电信
> > > > ```
> > > > 2022/10/10 09:11:08 Webhook调用失败，Err：Post "https://ddns-bot.vercel.app/api/hook/xxxxxxxx?": read tcp xxx.xxx.xxx.xxx:59092->76.76.21.61:443: read: connection reset by peer
> > > > ```
> > > > 
> > > > 
> > > >     
> > > >       
> > > >     
> > > > 
> > > >       
> > > >     
> > > > 
> > > >     
> > > >   
> > > > TG上最后收到的消息是 2022年8月25 号。。。
> > > > 在 US 的 VPS 上测试，能正常收到消息
> > > 
> > > 
> > > 自己研究了一下 搭了个bot 我这儿正常了 你试试吧 https://t.me/DDNS_Telegram_Bot
> > 
> > 
> > 这个怎么自己部署啊，部署到vps或者vercel有文档吗
> 
> 教程写好了 [https://github.com/wukibaka/ddns-telegram-bot/wiki/DDNS-TELEGRAM-BOT搭建教程](https://github.com/wukibaka/ddns-telegram-bot/wiki/DDNS-TELEGRAM-BOT%E6%90%AD%E5%BB%BA%E6%95%99%E7%A8%8B)

感谢大佬的分享
